[package]
name = "frunk_derives"
version = "0.0.1"
authors = ["Lloyd <lloydmeta@gmail.com>"]
description = "frunk_derives contains the custom derivations for certain traits in Frunk."
license = "MIT"
homepage = "https://github.com/lloydmeta/frunk"
keywords = [ "HList", "Generic", "derives"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11.4"
quote = "0.3.12"

[dependencies.frunk_core]
path = "../core"
version = "0.0.1"
