[package]
name = "frunk_derives"
version = "0.0.10"
authors = ["Lloyd <lloydmeta@gmail.com>"]
description = "frunk_derives contains the custom derivations for certain traits in Frunk."
license = "MIT"
documentation = "https://docs.rs/frunk_derives/0.0.10/frunk_derives/"
repository = "https://github.com/lloydmeta/frunk"
keywords = [ "HList", "Generic", "derives"]

[badges]
travis-ci = { repository = "lloydmeta/frunk" }

[lib]
proc-macro = true

[dependencies]
syn = "0.11.9"
quote = "0.3.15"

[dependencies.frunk_core]
path = "../core"
version = "0.0.9"
